# Sequence parameters
sequence_type: "icl_nuim.ICLNUIMSequence"

dataset_type: "TUM"
scene: "1n"
use_gt: False
pose_folder: "./treasure/orbslam2_record/lrkt1n/"
outdir: "./res/lrkt1n_ours/"

calib: [481.2, 480.0, 319.50, 239.50, 5000.0]

sequence_kwargs:
  path: "./data/ICL_NUIM/lr_kt1n/"
  start_frame: 0
  end_frame: -1
  first_tq: [-0.1, 1.3, 0.1, 0.0, -1.0, 0.0, 0.0]

# Network parameters (network structure, etc. will be inherited from the training config)
training_hypers: "./treasure/hyper.json"
using_epoch: 600

# Separate tracking and meshing.
run_async: false
# Enable visualization
vis: True
resolution: 4


# meshing
max_n_triangles: 4e6
max_std: 0.15 # 0.06


depth_cut_min: 0.5
depth_cut_max: 3.0

meshing_interval: 20
integrate_interval: 20

# Mapping parameters (See README.md for details)
mapping:
  bound_min: [-3.5, -0.5, -2.5]
  bound_max: [4.5, 3.5, 5.5]
  voxel_size: 0.1
  prune_min_vox_obs: 16
  ignore_count_th: 16.0
  encoder_count_th: 600.0

# Tracking parameters (See README.md for details)
tracking:
  iter_config:
    - {"n": 10, "type": [['rgb', 2]]}
    - {"n": 10, "type": [['sdf'], ['rgb', 1]]}
    - {"n": 50, "type": [['sdf'], ['rgb', 0]]}
  sdf:
    robust_kernel: "huber"
    robust_k: 5.0
    subsample: 0.5
  rgb:
    weight: 500.0
    robust_kernel: null
    robust_k: 0.01
    min_grad_scale: 0.0
    max_depth_delta: 0.2

